# Generated by Django 5.2.7 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0003_subsidyapplication_assigned_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyapplication',
            name='application_id',
            field=models.CharField(editable=False, max_length=26, unique=True),
        ),
    ]
