# Generated by Django 5.2.7 on 2025-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0004_alter_subsidyapplication_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Payment done', 'Payment done')], default='Pending', max_length=20, null=True),
        ),
    ]
