# Generated by Django 5.2.7 on 2025-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0007_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyapplication',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACCEPTED', 'Accepted')], default='UNDER_REVIEW', help_text='Current approval status', max_length=20),
        ),
    ]
