# Generated by Django 5.2.7 on 2025-11-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0008_subsidyapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidyapplication',
            name='status',
        ),
    ]
