# Generated by Django 5.2.7 on 2025-11-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0009_remove_subsidyapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Under Review', 'Under Review')], default='Pending', max_length=20),
        ),
    ]
