// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HomePage_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HomePage_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 1199, height: 649 })
    await driver.findElement(By.css(".Navbar:nth-child(2)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(3)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(4)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(5)")).click()
    await driver.findElement(By.css(".bg-green-600:nth-child(6)")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".flex-1")).click()
    await driver.findElement(By.css(".bg-green-600")).click()
    {
      const element = await driver.findElement(By.css(".bg-green-600"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(2)")).click()
    await driver.findElement(By.css(".lg\\3Ahidden > .relative")).click()
    await driver.executeScript("window.scrollTo(0,528.2166748046875)")
    await driver.findElement(By.css(".Navbar-mobile:nth-child(3)")).click()
    await driver.findElement(By.css(".lg\\3Apx-8")).click()
    await driver.findElement(By.css(".lg\\3Ahidden > .relative")).click()
    {
      const element = await driver.findElement(By.css(".lg\\3Ahidden > .relative"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".Navbar-mobile:nth-child(4)")).click()
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.executeScript("window.scrollTo(0,1729.5167236328125)")
    await driver.findElement(By.css(".Navbar-mobile:nth-child(5)")).click()
    await driver.findElement(By.css(".top-2\\.5")).click()
    {
      const element = await driver.findElement(By.css(".top-2\\.5"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".bg-green-600")).click()
    await driver.findElement(By.css(".pl-3")).click()
    await driver.findElement(By.css(".hover\\3A bg-\\[\\#145a32\\]")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".bg-green-600")).click()
    await driver.findElement(By.css(".bg-\\[\\#C3FFC8\\]:nth-child(1) > .w-32")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".bg-green-600")).click()
    await driver.findElement(By.css(".bg-\\[\\#F5F5DC\\]:nth-child(1) .bg-\\[\\#1B7A43\\]")).click()
    await driver.findElement(By.css(".bg-\\[\\#1B7A43\\] > span")).click()
    {
      const element = await driver.findElement(By.css(".bg-\\[\\#1B7A43\\] > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(3) > span")).click()
    {
      const element = await driver.findElement(By.css(".flex:nth-child(3) > span"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".FAQ-box:nth-child(1)")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(3)")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(5) > .text-gray-800")).click()
    await driver.findElement(By.css(".max-h-96 > .bg-\\[\\#F0F9E8\\]")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(7)")).click()
  })
})
