// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Notification_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Notification_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 898, height: 591 })
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    {
      const element = await driver.findElement(By.css(".bg-\\[\\#07843A\\]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".h-6")).click()
    await driver.findElement(By.css(".flex:nth-child(1) .text-sm")).click()
    await driver.findElement(By.css(".flex:nth-child(2) .text-sm")).click()
    await driver.findElement(By.css(".flex:nth-child(1) .w-4")).click()
    await driver.findElement(By.css(".bg-\\[\\#009500\\]")).click()
    await driver.findElement(By.css(".h-6")).click()
    await driver.findElement(By.css(".bg-red-600")).click()
    await driver.findElement(By.css(".bg-\\[\\#009500\\]")).click()
  })
})
