// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Officer_Gravience_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Officer_Gravience_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".lg\\3Ahidden > .relative")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("officer@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("@Harshil14")
    await driver.findElement(By.css(".right-3 > svg")).click()
    await driver.findElement(By.css(".right-3 > svg")).click()
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".p-2:nth-child(2)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".flex-wrap:nth-child(2)")).click()
    await driver.findElement(By.css(".py-2:nth-child(3)")).click()
    await driver.findElement(By.css(".py-2:nth-child(4)")).click()
    await driver.findElement(By.css(".py-2:nth-child(5)")).click()
    await driver.findElement(By.css(".pl-12")).click()
    await driver.findElement(By.css(".pl-12")).click()
    await driver.findElement(By.css(".pl-12")).click()
    await driver.findElement(By.css(".pl-12")).click()
    await driver.findElement(By.css(".pl-12")).click()
    await driver.findElement(By.css(".pl-12")).sendKeys("a")
  })
})
