// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Personal_Info_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Personal_Info_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css(".hover\\3Aunderline:nth-child(2)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("6354712136")
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".hover\\3A bg-gray-200:nth-child(1)")).click()
    await driver.findElement(By.id("btn1")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).sendKeys("608244")
    await driver.findElement(By.id("btn1")).click()
    await driver.findElement(By.css(".inline-flex")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .text-sm")).click()
    await driver.executeScript("window.scrollTo(0,213.1999969482422)")
    await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Tapi']")).click()
    }
    await driver.findElement(By.css(".min-w-\\[180px\\] option:nth-child(24)")).click()
    await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Surendranagar']")).click()
    }
    await driver.findElement(By.css(".flex:nth-child(2) option:nth-child(23)")).click()
    await driver.findElement(By.css(".min-w-\\[180px\\]:nth-child(3)")).click()
    await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Dhrangadhra']")).click()
    }
    await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12 > option:nth-child(5)")).click()
    await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Jasapar']")).click()
    }
    await driver.findElement(By.css(".flex:nth-child(4) option:nth-child(22)")).click()
    await driver.findElement(By.id("submit_btn")).click()
    await driver.findElement(By.id("submit_btn")).click()
  })
})
