// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Dashboard_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Dashboard_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    {
      const element = await driver.findElement(By.css(".lg\\3Ahidden"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css(".hover\\3Aunderline:nth-child(2)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("6354712136")
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".hover\\3A bg-gray-200:nth-child(1)")).click()
    await driver.findElement(By.id("btn1")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).sendKeys("483996")
    await driver.findElement(By.id("btn1")).click()
    {
      const element = await driver.findElement(By.id("btn1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".flex-wrap:nth-child(1)")).click()
    await driver.findElement(By.css(".rounded-lg")).click()
    await driver.findElement(By.css(".sm\\3Aw-9")).click()
    await driver.findElement(By.css(".h-6")).click()
    await driver.findElement(By.css(".shadow-xl > .flex")).click()
    await driver.findElement(By.css(".text-gray-500 > .w-6")).click()
    await driver.findElement(By.css(".gap-4 > .relative")).click()
    await driver.findElement(By.css(".sm\\3Aw-9")).click()
    await driver.findElement(By.css(".sm\\3Aw-9")).click()
  })
})
