# Generated by Django 5.2.7 on 2025-11-11 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy_name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('application_id', models.CharField(max_length=20, unique=True)),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Under Review', max_length=20)),
            ],
        ),
    ]
