// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HomepageTest', function() {
  describe(
  'Something',
  { timeout: 30000 },
  () => {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HomepageTest', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1034, height: 658 })
    await driver.findElement(By.css(".active")).click()
    await driver.findElement(By.css(".Navbar:nth-child(2)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(3)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(4)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(5)")).click()
    await driver.findElement(By.css(".Navbar:nth-child(1)")).click()
    await driver.findElement(By.css(".pl-3")).click()
    await driver.findElement(By.css(".hover\\3A bg-\\[\\#145a32\\]")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".flex-1")).click()
    await driver.findElement(By.css(".flex-1")).click()
    await driver.findElement(By.css(".bg-green-600")).click()
    await driver.findElement(By.css(".bg-\\[\\#C3FFC8\\]:nth-child(1) > .w-30")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".bg-green-600")).click()
    await driver.findElement(By.css(".bg-\\[\\#F5F5DC\\]:nth-child(1) .bg-\\[\\#1B7A43\\]")).click()
    await driver.findElement(By.css(".flex:nth-child(4)")).click()
    await driver.findElement(By.css(".bg-\\[\\#1B7A43\\] > span")).click()
    {
      const element = await driver.findElement(By.css(".bg-\\[\\#1B7A43\\] > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(3) > span")).click()
    await driver.findElement(By.css(".bg-green-700")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(1)")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(1)")).click()
    await driver.findElement(By.css(".space-y-4")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(3)")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(5) > .text-gray-800")).click()
    await driver.findElement(By.css(".FAQ-box:nth-child(7) > .text-gray-800")).click()
  })
})
