// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login_With_Mobile_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login_With_Mobile_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 1087, height: 713 })
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.css(".hover\\3Aunderline:nth-child(2)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("6354712136")
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".hover\\3A bg-gray-200:nth-child(1)")).click()
    await driver.findElement(By.id("btn1")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).sendKeys("712905")
    await driver.findElement(By.id("btn1")).click()
    {
      const element = await driver.findElement(By.id("btn1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".justify-center:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
