// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Officer_Login_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Officer_Login_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 1087, height: 713 })
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("officer@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("@Harshil14")
    await driver.findElement(By.css(".right-3 > svg")).click()
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".p-2:nth-child(2)")).click()
    await driver.findElement(By.id("btn6")).click()
  })
})
