// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Signup_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Signup_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 1034, height: 658 })
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.css(".text-black:nth-child(2)")).click()
    await driver.findElement(By.css(".p-2 > .w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".p-2 > .w-full:nth-child(1)")).sendKeys("Bhumi Patel")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("8799549950")
    await driver.findElement(By.css(".w-full:nth-child(3)")).click()
    await driver.findElement(By.css(".w-full:nth-child(3)")).sendKeys("bhumi@gmail.com")
    await driver.findElement(By.css(".relative > .mb-3")).click()
    await driver.findElement(By.css(".relative > .mb-3")).sendKeys("bhumi@2005")
    await driver.findElement(By.css(".relative:nth-child(5) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(5) > .w-full")).sendKeys("bhumi@2005")
    await driver.findElement(By.id("agree")).click()
    await driver.findElement(By.id("btn5")).click()
  })
})
