// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SubsidyRecommendation_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SubsidyRecommendation_Test', async function() {
    await driver.get("http://localhost:5173")
    await driver.manage().window().setRect({ width: 777, height: 497 })
    await driver.findElement(By.css(".inline-flex")).click()
    {
      const element = await driver.findElement(By.css(".inline-flex"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(5) > .text-sm")).click()
    await driver.findElement(By.name("income")).click()
    await driver.findElement(By.name("income")).sendKeys("10000")
    await driver.findElement(By.name("farmer_type")).click()
    {
      const dropdown = await driver.findElement(By.name("farmer_type"))
      await dropdown.findElement(By.xpath("//option[. = 'Medium Farmer']")).click()
    }
    await driver.findElement(By.css("option:nth-child(4)")).click()
    await driver.findElement(By.name("land_size")).click()
    await driver.findElement(By.name("land_size")).sendKeys("25")
    await driver.findElement(By.name("past_subsidies")).click()
    await driver.findElement(By.name("past_subsidies")).sendKeys("PM-Kisan")
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.name("crop_type")).click()
    await driver.findElement(By.name("crop_type")).sendKeys("Wheat")
    {
      const element = await driver.findElement(By.name("season"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("season"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("season"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("season")).click()
    {
      const dropdown = await driver.findElement(By.name("season"))
      await dropdown.findElement(By.xpath("//option[. = 'Rabi']")).click()
    }
    await driver.findElement(By.css("div:nth-child(2) > .w-full > option:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.name("soil_type"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("soil_type"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("soil_type"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("soil_type")).click()
    {
      const dropdown = await driver.findElement(By.name("soil_type"))
      await dropdown.findElement(By.xpath("//option[. = 'Desert']")).click()
    }
    await driver.findElement(By.css("div:nth-child(3) > .w-full > option:nth-child(6)")).click()
    {
      const element = await driver.findElement(By.name("water_sources"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("water_sources"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("water_sources"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("water_sources")).click()
    {
      const dropdown = await driver.findElement(By.name("water_sources"))
      await dropdown.findElement(By.xpath("//option[. = 'River']")).click()
    }
    await driver.findElement(By.css("div:nth-child(4) option:nth-child(5)")).click()
    {
      const element = await driver.findElement(By.name("state"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("state"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("state"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("state")).click()
    {
      const dropdown = await driver.findElement(By.name("state"))
      await dropdown.findElement(By.xpath("//option[. = 'Assam']")).click()
    }
    await driver.findElement(By.css("div:nth-child(5) option:nth-child(5)")).click()
    {
      const element = await driver.findElement(By.name("district"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("district"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("district"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("district")).click()
    {
      const dropdown = await driver.findElement(By.name("district"))
      await dropdown.findElement(By.xpath("//option[. = 'Barpeta']")).click()
    }
    await driver.findElement(By.css("div:nth-child(6) option:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.name("rainfall_region"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("rainfall_region"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("rainfall_region"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("rainfall_region")).click()
    {
      const dropdown = await driver.findElement(By.name("rainfall_region"))
      await dropdown.findElement(By.xpath("//option[. = 'Semi-arid']")).click()
    }
    await driver.findElement(By.css("div:nth-child(7) option:nth-child(5)")).click()
    {
      const dropdown = await driver.findElement(By.name("temperature_zone"))
      await dropdown.findElement(By.xpath("//option[. = 'Temperate']")).click()
    }
    await driver.findElement(By.css("div:nth-child(8) option:nth-child(4)")).click()
    {
      const element = await driver.findElement(By.name("district"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("district"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("district"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("district")).click()
    await driver.findElement(By.css(".shadow-2xl")).click()
    await driver.findElement(By.css(".hover\\3A bg-green-700")).click()
  })
})
