// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SubsidyPageTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SubsidyPageTest', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 939, height: 599 })
    await driver.findElement(By.css(".lg\\3Ahidden > .relative")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".inline-flex")).click()
    await driver.findElement(By.css(".flex:nth-child(4) > .text-sm")).click()
    await driver.findElement(By.css(".flex:nth-child(1) .bg-green-600:nth-child(1)")).click()
    await driver.findElement(By.css(".top-4")).click()
  })
})
