// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SubsidyProvider_Dashboard_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SubsidyProvider_Dashboard_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("ngo@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("@Harshil14")
    await driver.findElement(By.css(".right-3 > svg")).click()
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".p-2:nth-child(4)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".mt-4")).click()
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("PM-Kisan")
    await driver.findElement(By.name("amount")).click()
    await driver.findElement(By.name("amount")).sendKeys("24000")
    await driver.findElement(By.name("application_start_date")).click()
    await driver.findElement(By.name("application_start_date")).click()
    {
      const element = await driver.findElement(By.name("application_start_date"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.name("application_start_date")).click()
    await driver.findElement(By.name("application_start_date")).sendKeys("2025-11-18")
    await driver.findElement(By.name("application_end_date")).click()
    await driver.findElement(By.name("application_end_date")).sendKeys("2025-11-27")
    await driver.findElement(By.name("description")).click()
    await driver.findElement(By.name("description")).sendKeys("this subsidy gives 6000 per month")
    {
      const dropdown = await driver.findElement(By.css("div:nth-child(6) > .w-full"))
      await dropdown.findElement(By.xpath("//option[. = '-- Select Document --']")).click()
    }
    await driver.findElement(By.css(".bg-\\[\\#009500\\]:nth-child(1)")).click()
    await driver.findElement(By.css(".bg-gray-200")).click()
  })
})
