// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Subsidy_Provider_Report_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Subsidy_Provider_Report_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("ngo@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("@Harshil14")
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".p-2:nth-child(4)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".flex-wrap:nth-child(2)")).click()
    await driver.findElement(By.css(".flex-wrap:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".flex-wrap:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".pl-9")).click()
    await driver.findElement(By.css(".pl-9")).sendKeys("Rajesh Kumar")
    await driver.findElement(By.css(".whitespace-nowrap")).click()
    await driver.findElement(By.css(".bg-\\[\\#009500\\]:nth-child(1)")).click()
    await driver.findElement(By.css(".text-sm path")).click()
    await driver.findElement(By.css(".text-sm path")).click()
  })
})
