// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SubsidyProvider_PostNews_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SubsidyProvider_PostNews_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".top-5")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("ngo@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("@Harshil14")
    await driver.findElement(By.css(".right-3 > svg")).click()
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".p-2:nth-child(4)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".flex-wrap:nth-child(2)")).click()
    await driver.findElement(By.css(".mt-4")).click()
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("News")
    await driver.findElement(By.name("date")).click()
    await driver.findElement(By.name("date")).sendKeys("2025-11-14")
    await driver.findElement(By.css(".grid > div:nth-child(2)")).click()
    await driver.findElement(By.name("source")).click()
    await driver.findElement(By.name("source")).sendKeys("Gujrat Samachar")
    await driver.findElement(By.name("description")).click()
    await driver.findElement(By.name("description")).sendKeys("this is important news article")
    await driver.findElement(By.css(".flex-1:nth-child(2)")).click()
    await driver.findElement(By.css(".text-gray-500 > .text-2xl")).click()
  })
})
