// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('UserGravience_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('UserGravience_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app")
    await driver.manage().window().setRect({ width: 1144, height: 657 })
    await driver.findElement(By.css(".flex:nth-child(6)")).click()
    await driver.findElement(By.css(".text-semibold")).click()
    await driver.findElement(By.css("div:nth-child(1) > .border")).click()
    await driver.findElement(By.css("div:nth-child(1) > .border")).sendKeys("topic1")
    await driver.findElement(By.css("div:nth-child(2) > .mt-1")).click()
    await driver.findElement(By.css("div:nth-child(2) > .mt-1")).sendKeys("this subsidy is not good")
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.css(".py-2:nth-child(1)")).click()
    await driver.findElement(By.css(".py-3:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".py-3:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".py-3:nth-child(2) > .w-full")).click()
    await driver.executeScript("window.scrollTo(0,177.6666717529297)")
    await driver.findElement(By.css(".group:nth-child(1) .bg-white")).click()
  })
})
