// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Forgot_Password_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Forgot_Password_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 1087, height: 713 })
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.css(".hover\\3Aunderline:nth-child(1)")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).sendKeys("priyanshigothi2001@gmail.com")
    await driver.findElement(By.id("btn3")).click()
    await driver.findElement(By.css(".bg-white")).click()
    await driver.findElement(By.css(".bg-white")).sendKeys("699766")
    await driver.findElement(By.id("btn2")).click()
    await driver.findElement(By.css(".border-gray-300")).click()
    await driver.findElement(By.css(".border-gray-300")).sendKeys("namra@2004")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("namra@2004")
    await driver.findElement(By.css(".relative:nth-child(2) svg")).click()
    await driver.findElement(By.css(".relative:nth-child(1) svg")).click()
    await driver.findElement(By.id("btn4")).click()
    await driver.findElement(By.id("btn4")).click()
  })
})
