// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('UserProfile_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('UserProfile_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 1034, height: 658 })
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.css(".flex-wrap:nth-child(2)")).click()
    await driver.findElement(By.css(".lg\\3Aw-80 > .focus\\3Aring-2")).click()
    await driver.findElement(By.css(".lg\\3Aw-80 > .focus\\3Aring-2")).sendKeys("12345678913")
    await driver.findElement(By.css(".p-8")).click()
    await driver.findElement(By.css(".lg\\3Aw-80 > .focus\\3Aring-2")).click()
    await driver.findElement(By.css(".lg\\3Aw-80 > .focus\\3Aring-2")).sendKeys("123456789134")
    {
      const element = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12")).click()
    await driver.findElement(By.css(".lg\\3Aw-80 > .focus\\3Aring-2")).click()
    {
      const element = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Gujarat']")).click()
    }
    await driver.findElement(By.css(".lg\\3Amin-w-\\[180px\\] option:nth-child(13)")).click()
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(2) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Surendranagar']")).click()
    }
    await driver.findElement(By.css(".min-w-\\[180px\\] option:nth-child(23)")).click()
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Dhrangadhra']")).click()
    }
    await driver.findElement(By.css(".flex-1:nth-child(3) > .h-12 > option:nth-child(5)")).click()
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex-1:nth-child(4) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Jasapar']")).click()
    }
    await driver.findElement(By.css(".flex:nth-child(4) option:nth-child(22)")).click()
    await driver.findElement(By.css(".md\\3Aw-full")).click()
    await driver.findElement(By.css(".md\\3Aw-full")).sendKeys("Jasapar")
    await driver.findElement(By.css(".flex:nth-child(1) > .px-3")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .px-3")).sendKeys("25")
    {
      const element = await driver.findElement(By.css(".grid > .flex:nth-child(2) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".grid > .flex:nth-child(2) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".grid > .flex:nth-child(2) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".grid > .flex:nth-child(2) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".grid > .flex:nth-child(2) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Hectares']")).click()
    }
    await driver.findElement(By.css(".grid > .flex:nth-child(2) option:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".grid > .flex:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".grid > .flex:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".grid > .flex:nth-child(3) > .h-12"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".grid > .flex:nth-child(3) > .h-12")).click()
    {
      const dropdown = await driver.findElement(By.css(".grid > .flex:nth-child(3) > .h-12"))
      await dropdown.findElement(By.xpath("//option[. = 'Black']")).click()
    }
    await driver.findElement(By.css(".grid > .flex:nth-child(3) option:nth-child(3)")).click()
    await driver.findElement(By.css(".w-12")).click()
    await driver.findElement(By.css(".grid > div:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".grid > div:nth-child(1) > .w-full")).sendKeys("1234658997")
    await driver.findElement(By.css(".grid > div:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".grid > div:nth-child(2) > .w-full")).sendKeys("UTIB0000400")
    await driver.findElement(By.css(".mt-4 > .w-full")).click()
    await driver.findElement(By.css(".grid > div:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".mt-4 > .w-full")).click()
    await driver.findElement(By.css(".mt-4 > .w-full")).sendKeys("Axis Bank")
    await driver.findElement(By.css(".flex:nth-child(1) > .border-2")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .border-2 .text-sm")).click()
    await driver.findElement(By.id("submit_btn")).click()
  })
})
