// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Signup_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Signup_Test', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1087, height: 713 })
    await driver.findElement(By.css(".px-8")).click()
    await driver.findElement(By.css(".text-black:nth-child(2)")).click()
    await driver.findElement(By.css(".p-2 > .w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".p-2 > .w-full:nth-child(1)")).sendKeys("Rinku Patel")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("7624078920")
    await driver.findElement(By.css(".w-full:nth-child(3)")).click()
    await driver.findElement(By.css(".w-full:nth-child(3)")).sendKeys("rinku@gmail.com")
    await driver.findElement(By.css(".relative > .mb-3")).click()
    await driver.findElement(By.css(".relative > .mb-3")).sendKeys("rinku@2005")
    await driver.findElement(By.css(".relative:nth-child(5) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(5) > .w-full")).sendKeys("rinku@2005")
    await driver.findElement(By.css(".relative:nth-child(5) svg")).click()
    await driver.findElement(By.css("path:nth-child(2)")).click()
    await driver.findElement(By.id("agree")).click()
    await driver.findElement(By.id("btn5")).click()
  })
})
