// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Support_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Support_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".relative")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css(".flex:nth-child(6)")).click()
    await driver.findElement(By.css(".text-semibold")).click()
    {
      const element = await driver.findElement(By.css(".text-semibold"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("div:nth-child(1) > .border")).click()
    await driver.findElement(By.css("div:nth-child(1) > .border")).sendKeys("Late subsidy")
    await driver.findElement(By.css("div:nth-child(2) > .mt-1")).click()
    await driver.findElement(By.css("div:nth-child(2) > .mt-1")).sendKeys("subsidy amount received late")
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.css(".py-3:nth-child(3)")).click()
    await driver.findElement(By.css(".py-3:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".py-3:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".py-3:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".py-3:nth-child(3) > .w-full")).click()
    await driver.findElement(By.css(".group:nth-child(1) > .relative")).click()
    await driver.findElement(By.css(".group:nth-child(2) > .relative")).click()
  })
})
