// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Documents_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Documents_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    {
      const element = await driver.findElement(By.css(".lg\\3Ahidden > .relative"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".lg\\3Ahidden > .relative")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("priyanshigothi2001@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("namra@2004")
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".hover\\3A bg-gray-200:nth-child(1)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".flex-wrap:nth-child(3)")).click()
    await driver.findElement(By.css(".py-2")).click()
    await driver.findElement(By.name("document_type")).click()
    {
      const dropdown = await driver.findElement(By.name("document_type"))
      await dropdown.findElement(By.xpath("//option[. = 'Receipt of fee paid for residue testing']")).click()
    }
    await driver.findElement(By.css("option:nth-child(5)")).click()
    await driver.findElement(By.css(".mb-4:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".mb-4:nth-child(2) > .w-full")).sendKeys("1")
    await driver.findElement(By.css(".mb-6 > .w-full")).click()
    await driver.findElement(By.css(".flex-1:nth-child(1)")).click()
    assert(await driver.switchTo().alert().getText() == "Failed to upload document. Please try again.")
    await driver.findElement(By.css(".flex-1:nth-child(1)")).click()
    assert(await driver.switchTo().alert().getText() == "Failed to upload document. Please try again.")
    await driver.findElement(By.css(".bg-gray-200")).click()
  })
})
