// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Subsidy_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Subsidy_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    await driver.findElement(By.css(".lg\\3Ahidden")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css(".mt-5")).click()
    await driver.findElement(By.css(".flex:nth-child(4)")).click()
    await driver.findElement(By.css(".md\\3Apx-3:nth-child(3)")).click()
    await driver.findElement(By.css(".md\\3Apx-3:nth-child(4)")).click()
    await driver.findElement(By.css(".md\\3Apx-4:nth-child(1)")).click()
    await driver.findElement(By.css(".md\\3Apx-4:nth-child(8)")).click()
    await driver.findElement(By.css(".md\\3Apx-4:nth-child(8)")).click()
    await driver.findElement(By.css(".md\\3Apx-4:nth-child(8)")).click()
    await driver.findElement(By.css(".md\\3Apx-4:nth-child(8)")).click()
    await driver.findElement(By.css(".md\\3Apx-4:nth-child(1)")).click()
    await driver.findElement(By.css(".flex:nth-child(1) .bg-green-600:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".flex:nth-child(1) .bg-green-600:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".px-8")).click()
    {
      const element = await driver.findElement(By.css(".justify-between"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".justify-between"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".justify-between"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".justify-between")).click()
    await driver.findElement(By.css(".px-6")).click()
    await driver.findElement(By.id("ownership")).click()
    {
      const dropdown = await driver.findElement(By.id("ownership"))
      await dropdown.findElement(By.xpath("//option[. = 'Owned']")).click()
    }
    await driver.findElement(By.css("#ownership > option:nth-child(2)")).click()
    await driver.findElement(By.css(".hover\\3A bg-green-700")).click()
    await driver.findElement(By.css(".hover\\3A bg-green-700")).click()
    await driver.findElement(By.css(".py-2")).click()
    await driver.findElement(By.css(".mb-4:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".mb-4:nth-child(2) > .w-full")).sendKeys("1")
    await driver.findElement(By.css(".max-w-md > div")).click()
    await driver.findElement(By.css(".mb-6 > .w-full")).click()
    await driver.findElement(By.css(".flex-1:nth-child(1)")).click()
    await driver.findElement(By.css(".px-8")).click()
  })
})
