// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User_Change_Password_Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User_Change_Password_Test', async function() {
    await driver.get("https://krushi-setu.vercel.app/")
    await driver.manage().window().setRect({ width: 988, height: 649 })
    {
      const element = await driver.findElement(By.css(".lg\\3Ahidden"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".lg\\3Ahidden > .relative")).click()
    await driver.findElement(By.css(".Navbar-mobile:nth-child(6)")).click()
    await driver.findElement(By.css("form > .p-2")).click()
    await driver.findElement(By.css("form > .p-2")).sendKeys("priyanshigothi2001@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("namra@2004")
    await driver.findElement(By.css(".pr-12")).click()
    await driver.findElement(By.css(".hover\\3A bg-gray-200:nth-child(1)")).click()
    await driver.findElement(By.id("btn6")).click()
    await driver.findElement(By.css(".sm\\3Aw-9")).click()
    await driver.findElement(By.css("li:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(1) > .w-full")).sendKeys("namra@2004")
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(2) > .w-full")).sendKeys("namra@2005")
    await driver.findElement(By.css(".relative:nth-child(2) svg")).click()
    await driver.findElement(By.css("path:nth-child(2)")).click()
    await driver.findElement(By.css(".relative:nth-child(3) > .w-full")).click()
    await driver.findElement(By.css(".relative:nth-child(3) > .w-full")).sendKeys("namra@2005")
    await driver.findElement(By.css(".relative:nth-child(3) svg")).click()
    await driver.findElement(By.css(".relative:nth-child(3) svg")).click()
    await driver.findElement(By.css(".text-white")).click()
    await driver.findElement(By.css(".text-white")).click()
    await driver.findElement(By.css(".top-4")).click()
  })
})
